---
- hosts: server
  become: true
  tasks:
   - name: create blank file
     file:
       path: "/ans.txt"
       state: touch
       mode: 0755
       owner: root
  tasks:
    - name: content
      copy:
         dest: "/ans.txt"
         content: |
           This is test from ansible playbook
